-- MySQL Script generated by MySQL Workbench
-- Sun Jun 24 15:16:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project_catalog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `project_catalog` ;

-- -----------------------------------------------------
-- Schema project_catalog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_catalog` DEFAULT CHARACTER SET utf8 ;
USE `project_catalog` ;

-- -----------------------------------------------------
-- Table `project_catalog`.`betreuer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`betreuer` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`betreuer` (
  `Immatrikulation` INT(11) NOT NULL,
  `Meinung` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Immatrikulation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`cathegory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`cathegory` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`cathegory` (
  `idcathegory` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcathegory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`course` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`course` (
  `ID` INT(11) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Semester` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`user` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`user` (
  `idUser` INT(11) NOT NULL,
  `Userpasswort` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`course_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`course_has_user` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`course_has_user` (
  `course_ID` INT(11) NOT NULL,
  `User_idUser` INT(11) NOT NULL,
  PRIMARY KEY (`course_ID`, `User_idUser`),
  INDEX `fk_course_has_User_User1_idx` (`User_idUser` ASC),
  INDEX `fk_course_has_User_course1_idx` (`course_ID` ASC),
  CONSTRAINT `fk_course_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `project_catalog`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_has_User_course1`
    FOREIGN KEY (`course_ID`)
    REFERENCES `project_catalog`.`course` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`supervisor` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`supervisor` (
  `Immatrikulation` INT(11) NOT NULL,
  `Meinung` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Immatrikulation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`major` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`major` (
  `idMajor` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Supervisor_Immatrikulation` INT(11) NOT NULL,
  PRIMARY KEY (`idMajor`, `Supervisor_Immatrikulation`),
  INDEX `fk_Major_Supervisor1_idx` (`Supervisor_Immatrikulation` ASC),
  CONSTRAINT `fk_Major_Supervisor1`
    FOREIGN KEY (`Supervisor_Immatrikulation`)
    REFERENCES `project_catalog`.`supervisor` (`Immatrikulation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`project` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`project` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` ENUM('Offen', 'Akzeptiert', 'In Bearbeitung') NOT NULL,
  `start` DATE NULL,
  `end` DATE NOT NULL,
  `description` TEXT NOT NULL,
  `cathegory_id` INT(11) NULL COMMENT 'NULL',
  `course_id` INT(11) NULL COMMENT 'NULL',
  PRIMARY KEY (`id`),
  INDEX `fk_project_cathegory1_idx` (`cathegory_id` ASC),
  INDEX `fk_project_course1_idx` (`course_id` ASC),
  UNIQUE INDEX `cathegory_id_UNIQUE` (`cathegory_id` ASC),
  CONSTRAINT `fk_project_cathegory1`
    FOREIGN KEY (`cathegory_id`)
    REFERENCES `project_catalog`.`cathegory` (`idcathegory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `project_catalog`.`course` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`project_has_major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`project_has_major` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`project_has_major` (
  `project_Projekt  ID` INT(11) NOT NULL,
  `project_cathegory_idcathegory` INT(11) NOT NULL,
  `project_course_ID` INT(11) NOT NULL,
  `Major_idMajor` INT(11) NOT NULL,
  `Major_Supervisor_Immatrikulation` INT(11) NOT NULL,
  PRIMARY KEY (`project_Projekt  ID`, `project_cathegory_idcathegory`, `project_course_ID`, `Major_idMajor`, `Major_Supervisor_Immatrikulation`),
  INDEX `fk_project_has_Major_Major1_idx` (`Major_idMajor` ASC, `Major_Supervisor_Immatrikulation` ASC),
  INDEX `fk_project_has_Major_project1_idx` (`project_Projekt  ID` ASC, `project_cathegory_idcathegory` ASC, `project_course_ID` ASC),
  CONSTRAINT `fk_project_has_Major_Major1`
    FOREIGN KEY (`Major_idMajor` , `Major_Supervisor_Immatrikulation`)
    REFERENCES `project_catalog`.`major` (`idMajor` , `Supervisor_Immatrikulation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_Major_project1`
    FOREIGN KEY (`project_Projekt  ID` , `project_cathegory_idcathegory` , `project_course_ID`)
    REFERENCES `project_catalog`.`project` (`id` , `cathegory_id` , `course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`projektart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`projektart` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`projektart` (
  `ID` INT(11) NOT NULL,
  `Robotik` VARCHAR(45) NOT NULL,
  `Gewinnspiel` VARCHAR(45) NOT NULL,
  `Software` VARCHAR(45) NOT NULL,
  `webentwicklung` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`studiengang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`studiengang` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`studiengang` (
  `ID` INT(11) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `anzahlprjekt` VARCHAR(45) NOT NULL,
  `Anzahlbetreuer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`supervisorproject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`supervisorproject` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`supervisorproject` (
  `Supervisor_Immatrikulation` INT(11) NOT NULL,
  `project_Projekt  ID` INT(11) NOT NULL,
  PRIMARY KEY (`Supervisor_Immatrikulation`, `project_Projekt  ID`),
  INDEX `fk_Supervisor_has_project_project1_idx` (`project_Projekt  ID` ASC),
  INDEX `fk_Supervisor_has_project_Supervisor1_idx` (`Supervisor_Immatrikulation` ASC),
  CONSTRAINT `fk_Supervisor_has_project_Supervisor1`
    FOREIGN KEY (`Supervisor_Immatrikulation`)
    REFERENCES `project_catalog`.`supervisor` (`Immatrikulation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supervisor_has_project_project1`
    FOREIGN KEY (`project_Projekt  ID`)
    REFERENCES `project_catalog`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`tags` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`tags` (
  `idTags` INT(11) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTags`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`tagsproject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`tagsproject` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`tagsproject` (
  `Tags_idTags` INT(11) NOT NULL,
  `project_Projekt  ID` INT(11) NOT NULL,
  PRIMARY KEY (`Tags_idTags`, `project_Projekt  ID`),
  INDEX `fk_Tags_has_project_project1_idx` (`project_Projekt  ID` ASC),
  INDEX `fk_Tags_has_project_Tags1_idx` (`Tags_idTags` ASC),
  CONSTRAINT `fk_Tags_has_project_Tags1`
    FOREIGN KEY (`Tags_idTags`)
    REFERENCES `project_catalog`.`tags` (`idTags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tags_has_project_project1`
    FOREIGN KEY (`project_Projekt  ID`)
    REFERENCES `project_catalog`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_catalog`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_catalog`.`test` ;

CREATE TABLE IF NOT EXISTS `project_catalog`.`test` (
  `name` VARCHAR(45) NULL,
  `age` INT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
